[package]
name = "pong-tutorial"
version = "0.1.0"
authors = ["Malik"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst
